# Generated by Django 3.2 on 2024-03-04 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'категория (тип) произведения',
                'verbose_name_plural': 'Категории (типы) произведений',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'жанр произведения',
                'verbose_name_plural': 'Жанры произведений',
            },
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('year', models.IntegerField(max_length=4, verbose_name='Год выпуска')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='reviews.categories', verbose_name='Slug категории')),
                ('genre_name', models.ManyToManyField(to='reviews.Genres', verbose_name='Slug жанра')),
            ],
            options={
                'verbose_name': 'произведение',
                'verbose_name_plural': 'Произведения',
            },
        ),
    ]
