# Generated by Django 3.2 on 2024-03-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.IntegerField(default=0, null=True, verbose_name='Средний рейтинг'),
        ),
    ]
