# Generated by Django 3.2 on 2024-03-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20240304_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='genre_name',
        ),
        migrations.AddField(
            model_name='titles',
            name='genre_name',
            field=models.ManyToManyField(to='reviews.Genres', verbose_name='Slug жанра'),
        ),
    ]
