# Generated by Django 3.2 on 2024-03-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
